
/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 ** SPDX-License-Identifier: BSD-2-Clause
 */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_SEL4_ARCH_INVOCATION_H
#define __LIBSEL4_SEL4_ARCH_INVOCATION_H
enum sel4_arch_invocation_label {
    X86PDPTMap = nInvocationLabels,
    X86PDPTUnmap,
    nSeL4ArchInvocationLabels
};

#endif /* __LIBSEL4_SEL4_ARCH_INVOCATION_H */
